### ISSUE TITLE
APIError: No idToken2 or coralUserId found

### ISSUE THREAD

**Issue by chococat4** [spacemeowx2/s3si.ts#103]
When running the script, I've been getting this response every time
```
APIError: No idToken2 or coralUserId found. Please try again later. (undefined, undefined) 
Response:  Response {
  body: ReadableStream { locked: true },
  bodyUsed: true,
  headers: Headers {
    allow: "POST, OPTIONS",
    "content-type": "application/json",
    "cross-origin-opener-policy": "same-origin",
    date: "Fri, 20 Dec 2024 02:09:22 GMT",
    "referrer-policy": "same-origin",
    server: "gunicorn",
    vary: "Accept-Encoding, origin",
    via: "1.1 google",
    "x-content-type-options": "nosniff",
    "x-frame-options": "DENY"
  },
  ok: true,
  redirected: false,
  status: 200,
  statusText: "OK",
  url: "https://api-lp1.znc.srv.nintendo.net/v3/Account/Login"
} 
Body:  {
  status: 9427,
  errorMessage: "Upgrade required.",
  correlationId: "6b0a59eb-8e8e9cc6"
}
error: Uncaught (in promise) Error: No idToken2 or coralUserId found. Please try again later. (undefined, undefined)
      throw new APIError({
            ^
    at getIdToken2 (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/iksm.ts:222:13)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async retry (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/utils.ts:70:14)
    at async getGToken (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/iksm.ts:278:35)
    at async Splatnet3.fetchToken (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/splatnet3.ts:101:56)
    at async Splatnet3.request (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/splatnet3.ts:86:9)
    at async Splatnet3.getBankaraBattleHistories (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/splatnet3.ts:223:18)
    at async https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/GameFetcher.ts:104:61
    at async Mutex.use (https://deno.land/x/semaphore@v1.1.2/semaphore.ts:45:14)
    at async GameFetcher.updateRank (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/GameFetcher.ts:69:7)
```

**Comment by Lastorder-DC** [comment]
frozenpandaman/s3s#198

**Comment by spacemeowx2** [comment]
Fixed on main in 5c6645d (0.6.0) by replacing the obsolete authentication flow with the current encrypted nxapi flow, with real-account login, SplatNet access, and local export verified.
