### ISSUE TITLE
Weapon not found

### ISSUE THREAD

**Issue by tpnonthealps** [spacemeowx2/s3si.ts#33]
![螢幕截圖 2022-11-26 21 37 19](https://user-images.githubusercontent.com/7851076/204091744-c339d507-839b-4c5c-8435-0f58426b0d00.png)
````
Fetching battle list...
Exported stat.ink: 4
Fetching coop battle list...
Error: Weapon not found: 14式竹筒槍‧甲
    at StatInkExporter.mapCoopWeapon (file:///app/src/exporters/stat.ink.ts:477:13)
    at async Promise.all (index 1)
    at async StatInkExporter.mapCoopPlayer (file:///app/src/exporters/stat.ink.ts:503:16)
    at async Promise.all (index 0)
    at async StatInkExporter.mapCoop (file:///app/src/exporters/stat.ink.ts:641:16)
    at async StatInkExporter.exportGame (file:///app/src/exporters/stat.ink.ts:202:20)
    at async step (file:///app/src/app.ts:323:23)
    at async App.exportGameList (file:///app/src/app.ts:338:9)
    at async showError (file:///app/src/utils.ts:75:12)
    at async Promise.all (index 0)

Failed to export to stat.ink: Error: Weapon not found: 14式竹筒槍‧甲
    at StatInkExporter.mapCoopWeapon (file:///app/src/exporters/stat.ink.ts:477:13)
    at async Promise.all (index 1)
    at async StatInkExporter.mapCoopPlayer (file:///app/src/exporters/stat.ink.ts:503:16)
    at async Promise.all (index 0)
    at async StatInkExporter.mapCoop (file:///app/src/exporters/stat.ink.ts:641:16)
    at async StatInkExporter.exportGame (file:///app/src/exporters/stat.ink.ts:202:20)
    at async step (file:///app/src/app.ts:323:23)
    at async App.exportGameList (file:///app/src/app.ts:338:9)
    at async showError (file:///app/src/utils.ts:75:12)
Exported stat.ink: 0
    at async Promise.all (index 0)
Error: Weapon not found: 14式竹筒槍‧甲
    at StatInkExporter.mapCoopWeapon (file:///app/src/exporters/stat.ink.ts:477:13)
    at async Promise.all (index 1)
    at async StatInkExporter.mapCoopPlayer (file:///app/src/exporters/stat.ink.ts:503:16)
    at async Promise.all (index 0)
    at async StatInkExporter.mapCoop (file:///app/src/exporters/stat.ink.ts:641:16)
    at async StatInkExporter.exportGame (file:///app/src/exporters/stat.ink.ts:202:20)
    at async step (file:///app/src/app.ts:323:23)
    at async App.exportGameList (file:///app/src/app.ts:338:9)
    at async showError (file:///app/src/utils.ts:75:12)
    at async Promise.all (index 0)
error: Uncaught (in promise) Error: Weapon not found: 14式竹筒槍‧甲
      throw new Error(`Weapon not found: ${name}`);
            ^
    at StatInkExporter.mapCoopWeapon (file:///app/src/exporters/stat.ink.ts:477:13)
    at async Promise.all (index 1)
    at async StatInkExporter.mapCoopPlayer (file:///app/src/exporters/stat.ink.ts:503:16)
    at async Promise.all (index 0)
    at async StatInkExporter.mapCoop (file:///app/src/exporters/stat.ink.ts:641:16)
    at async StatInkExporter.exportGame (file:///app/src/exporters/stat.ink.ts:202:20)
    at async step (file:///app/src/app.ts:323:23)
    at async App.exportGameList (file:///app/src/app.ts:338:9)
    at async showError (file:///app/src/utils.ts:75:12)
    at async Promise.all (index 0)
````

**Comment by spacemeowx2** [comment]
```
14式竹筒槍·甲
14式竹筒槍‧甲
```
The only difference is the dot. I'll try to fix it.

**Comment by spacemeowx2** [comment]
And which version do you run? I failed to reproduce the problem

**Comment by tpnonthealps** [comment]
> And which version do you run? I failed to reproduce the problem

`ba43bb6c5542b7b5ce6301c03f1e69c90bf0b216`

**Comment by spacemeowx2** [comment]
Should be fixed
