### ISSUE TITLE
Error: The provided session_token_code is invalid.

### ISSUE THREAD

**Issue by laxect** [spacemeowx2/s3si.ts#4]
When [genSessionError](https://github.com/spacemeowx2/s3si.ts/blob/main/src/iksm.ts#L342), The Nintendo API will report an error:

```js
{
  error: "invalid_request",
  error_description: "The provided session_token_code is invalid"
}
```

And cause the following exception.

```
Error: No session token found
    at loginManually (file:///home/gyara/projects/wakare/s3si.ts/src/iksm.ts:78:11)
    at async App.run (file:///home/gyara/projects/wakare/s3si.ts/src/app.ts:302:28)
    at async showError (file:///home/gyara/projects/wakare/s3si.ts/src/utils.ts:68:5)
    at async file:///home/gyara/projects/wakare/s3si.ts/s3si.ts:40:1
error: Uncaught (in promise) Error: No session token found
    throw new Error("No session token found");
          ^
    at loginManually (file:///home/gyara/projects/wakare/s3si.ts/src/iksm.ts:78:11)
    at async App.run (file:///home/gyara/projects/wakare/s3si.ts/src/app.ts:302:28)
    at async showError (file:///home/gyara/projects/wakare/s3si.ts/src/utils.ts:68:5)
    at async file:///home/gyara/projects/wakare/s3si.ts/s3si.ts:40:1
```

**Comment by spacemeowx2** [comment]
My url safe base64 encode function is buggy. I'm lucky because none of the 4 times I logged in before triggered this issue.
