### ISSUE TITLE
Error: No idToken2 found

### ISSUE THREAD

**Issue by QueenLinuxGlitch** [spacemeowx2/s3si.ts#69]
**Describe the bug**
When running, even after resetting profile.json

Fetching battle list...

APIError: No idToken2 found
Response:  Response {
  body: ReadableStream { locked: true },
  bodyUsed: true,
  headers: Headers {
  allow: "POST, OPTIONS",
  "content-type": "application/json",
  date: "Wed, 24 May 2023 02:28:25 GMT",
  "referrer-policy": "same-origin",
  server: "gunicorn",
  vary: "Accept-Encoding, Origin",
  via: "1.1 google",
  "x-content-type-options": "nosniff",
  "x-frame-options": "DENY"
},
  ok: true,
  redirected: false,
  status: 200,
  statusText: "OK",
  url: "https://api-lp1.znc.srv.nintendo.net/v3/Account/Login"
}
Body:  {
  status: 9403,
  errorMessage: "Invalid token.",
  correlationId: "d42fe333-29c0a73f"
}
error: Uncaught (in promise) Error: No idToken2 found
      throw new APIError({
            ^
    at getIdToken2 (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/iksm.ts:216:13)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async retry (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/utils.ts:46:14)
    at async getGToken (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/iksm.ts:269:20)
    at async Splatnet3.fetchToken (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/splatnet3.ts:101:56)
    at async Splatnet3.request (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/splatnet3.ts:86:9)
    at async Splatnet3.getBattleList (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/splatnet3.ts:168:12)
    at async App.exportOnce (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/app.ts:166:24)
    at async App.monitor (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/app.ts:296:7)
    at async App.run (https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/src/app.ts:332:7)

**Comment by southpawfishel** [comment]
Seeing the same as of a few hours ago

**Comment by spacemeowx2** [comment]
https://github.com/frozenpandaman/s3s/issues/125
