### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by cooku** [spacemeowx2/s3si.ts#86]
root@Ubuntu:/home/s3sits# deno run -Ar s3si.ts [options]
TypeError: Cannot read properties of undefined (reading 'length')
    at getIdToken2 (file:///home/s3sits/src/iksm.ts:223:82)
    at eventLoopTick (ext:core/01_core.js:178:11)
    at async retry (file:///home/s3sits/src/utils.ts:46:14)
    at async getGToken (file:///home/s3sits/src/iksm.ts:275:35)
    at async Splatnet3.fetchToken (file:///home/s3sits/src/splatnet3.ts:101:56)
    at async Splatnet3.request (file:///home/s3sits/src/splatnet3.ts:86:9)
    at async Splatnet3.getBankaraBattleHistories (file:///home/s3sits/src/splatnet3.ts:223:18)
    at async file:///home/s3sits/src/GameFetcher.ts:104:61
    at async Mutex.use (https://deno.land/x/semaphore@v1.1.1/semaphore.ts:45:19)
    at async GameFetcher.updateRank (file:///home/s3sits/src/GameFetcher.ts:69:7)
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
          `No idToken2 or coralUserId found. Please try again later. (${idToken2.length}, ${coralUserId.length})`,
                                                                                 ^
    at getIdToken2 (file:///home/s3sits/src/iksm.ts:223:82)
    at eventLoopTick (ext:core/01_core.js:178:11)
    at async retry (file:///home/s3sits/src/utils.ts:46:14)
    at async getGToken (file:///home/s3sits/src/iksm.ts:275:35)
    at async Splatnet3.fetchToken (file:///home/s3sits/src/splatnet3.ts:101:56)
    at async Splatnet3.request (file:///home/s3sits/src/splatnet3.ts:86:9)
    at async Splatnet3.getBankaraBattleHistories (file:///home/s3sits/src/splatnet3.ts:223:18)
    at async file:///home/s3sits/src/GameFetcher.ts:104:61
    at async Mutex.use (https://deno.land/x/semaphore@v1.1.1/semaphore.ts:45:19)
    at async GameFetcher.updateRank (file:///home/s3sits/src/GameFetcher.ts:69:7)

**Comment by spacemeowx2** [comment]
Should be fixed, please try again
